name: "suvi"

on:
  workflow_dispatch:

jobs:
  download:
    strategy:
      matrix:
        product: 
          - suvi-primary-094
          - suvi-primary-131
          - suvi-primary-171
          - suvi-primary-195
          - suvi-primary-284
          - suvi-primary-304

          - suvi-secondary-094
          - suvi-secondary-131
          - suvi-secondary-171
          - suvi-secondary-195
          - suvi-secondary-284
          - suvi-secondary-304
          
    runs-on: "ubuntu-latest"
    steps:
      - name: "apt: install dependencies"
        run: |
          sudo apt-get update && sudo apt-get install -y \
            ffmpeg
        
      - name: "curl: download '${{ matrix.product }}.mp4'"
        run: curl -sSL $(curl -sSL https://services.swpc.noaa.gov/products/animations/${{ matrix.product }}.json | jq -r '.[] | "https://services.swpc.noaa.gov\(.url)"' | tr '\n' ' ') | ffmpeg -loglevel error -framerate 10 -f image2pipe -i - -c:v libx264 -r 30 -pix_fmt yuv420p -y ${{ matrix.product }}.mp4
  
      - name: "curl: ftp upload"
        shell: "bash"
        run: |
          curl \
            --ssl-reqd \
            --user "${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}" \
            --upload-file "${{ matrix.product }}.mp4" \
            "${{ secrets.FTP_HOST }}/videos/suvi/"
